### ISSUE TITLE
missing request.version_string attribute with urllib3 == 2.3.0 

### ISSUE THREAD

**Issue by tadams42** [kevin1024/vcrpy#888]
Tried re-creating cassette that causes error.

Works with `urllib3 == 2.2.3`.

Changing `boto3` version doesn't seem to have any impact.

Traceback:

```log
Aliases for entries in sys.path:
    <site>: /*********/.venv/lib/python3.12/site-packages/
Traceback (most recent call last):
    <site> botocore/httpsession.py:464    send           urllib_response = conn.urlopen(
    <site> urllib3/connectionpool.py:787  urlopen        response = self._make_request(
    <site> urllib3/connectionpool.py:551  _make_request  response.version_string,
AttributeError: 'VCRHTTPResponse' object has no attribute 'version_string'

During handling of the above exception, another exception occurred:

Aliases for entries in sys.path:
    <site>: /**********/.venv/lib/python3.12/site-packages/
    <pwd> : /**********/
Traceback (most recent call last):
    <pwd> *********/files_storage.py:125           upload                    response = self.s3_client.put_object(
    <site> botocore/client.py:569                          _api_call                 return self._make_api_call(operation_name, kwargs)
    <site> botocore/client.py:1005                         _make_api_call            http, parsed_response = self._make_request(
    <site> botocore/client.py:1029                         _make_request             return self._endpoint.make_request(operation_model, request_dict)
    <site> botocore/endpoint.py:119                        make_request              return self._send_request(request_dict, operation_model)
    <site> botocore/endpoint.py:200                        _send_request             while self._needs_retry(
    <site> botocore/endpoint.py:360                        _needs_retry              responses = self._event_emitter.emit(
    <site> botocore/hooks.py:412                           emit                      return self._emitter.emit(aliased_event_name, **kwargs)
    <site> botocore/hooks.py:256                           emit                      return self._emit(event_name, kwargs)
    <site> botocore/hooks.py:239                           _emit                     response = handler(**kwargs)
    <site> botocore/retryhandler.py:207                    __call__                  if self._checker(**checker_kwargs):
    <site> botocore/retryhandler.py:284                    __call__                  should_retry = self._should_retry(
    <site> botocore/retryhandler.py:307                    _should_retry             return self._checker(
    <site> botocore/retryhandler.py:363                    __call__                  checker_response = checker(
    <site> botocore/retryhandler.py:247                    __call__                  return self._check_caught_exception(
    <site> botocore/retryhandler.py:416                    _check_caught_exception   raise caught_exception
    <site> botocore/endpoint.py:279                        _do_get_response          http_response = self._send(request)
    <site> botocore/endpoint.py:383                        _send                     return self.http_session.send(request)
    <site> botocore/httpsession.py:509                     send                      raise HTTPClientError(error=e)
HTTPClientError: An HTTP Client raised an unhandled exception: 'VCRHTTPResponse' object has no attribute 'version_string'
```

**Comment by nschloe** [comment]
This is the relevant urllib3 PR: https://github.com/urllib3/urllib3/pull/3316

**Comment by sevbch** [comment]
Hi @nschloe,
I'm encountering the same issue.
Did you find a workaround? I tried downgrading `urllib3` dependency to v2.2.1, which is the [last release](https://urllib3.readthedocs.io/en/stable/changelog.html) before the PR you mention was merged, but it didn't work out.

**Comment by exslim** [comment]
Pull request to fix this issue: https://github.com/kevin1024/vcrpy/pull/889

**Comment by decitre** [comment]
I could workaround this issue with a:

```
@pytest.fixture(autouse=True)
def patch_VCRHTTPResponse_version_string():
    from vcr.stubs import VCRHTTPResponse
    if not hasattr(VCRHTTPResponse, 'version_string'):
        VCRHTTPResponse.version_string = None
    yield  
 ```

**Comment by kevin1024** [comment]
FYI the new release 7.0.0 should resolve this issue.
