### ISSUE TITLE
Failing with aiohttp 3.3.2

### ISSUE THREAD

**Issue by stj** [kevin1024/vcrpy#367]
Tried against vcrpy master 

```python
import pytest
import aiohttp.web

import vcr

async def hello(request):
    return aiohttp.web.Response(text='Hello, world')


@pytest.fixture
async def client(aiohttp_client):
    app = aiohttp.web.Application()
    app.router.add_get('/', hello)
    client = await aiohttp_client(app)
    return client


@vcr.use_cassette('localhost')
async def test_vcrpy(client): 
    await client.get('/')
```
When run raises

```
test_aiohttp.py:20: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../.virtualenvs/test/lib/python3.6/site-packages/aiohttp/test_utils.py:217: in request
    method, self.make_url(path), *args, **kwargs
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <aiohttp.client._RequestContextManager object at 0x7f53daa3cfc0>

    def __await__(self):
>       ret = self._coro.__await__()
E       AttributeError: 'generator' object has no attribute '__await__'
```

I managed to fix this for me by dropping Python 3.4 support and changed `vcr.stubs.aiohttp.__init__.vcr_request.new_requst` to use `async` and `await` syntax.

Tested against vcrpy==master, Python 3.6.5, aiohttp 3.3.2

**Comment by stj** [comment]
I pushed a fix to my [fork](https://github.com/stj/vcrpy/commit/9eccfc7348c583cacf523d5fee0f4e5f2ba0f16c). Though I believe it was a conscious decision to keep Python 3.4 compatibility when the fix for aiohttp 3.3 was original written. My fix ignores that and is probably not a solution you are looking for.

**Comment by lamenezes** [comment]
> Though I believe it was a conscious decision to keep Python 3.4 compatibility when the fix for aiohttp 3.3 was original written. My fix ignores that and is probably not a solution you are looking for.

We're trying to keep compatibility with python 3.4 as long as we can, but if we come across an issue that we definitely can't solve in 3.4 we might drop support to it.

> When run raises

I tried running the snippet you passed and the code on your fork but I got `fixture 'aiohttp_client' not found` on both. Could you fix that so we can proceed discussing this issue?

**Comment by stj** [comment]
https://github.com/aio-libs/aiohttp/blame/master/aiohttp/pytest_plugin.py#L328
That snippet will works with aiohttp 3.3.2. What version are you trying to test against?

**Comment by lamenezes** [comment]
I'm using aiohttp==3.3.2.

I think it would be better if you opened a PR and we moved this discussion there. What do you think?

**Comment by stj** [comment]
Created PR and changed `aiohttp_client` to `test_client` in snippet.
We can continue discussion in PR.
